### ISSUE TITLE
Link Objects to Rackspace

### ISSUE THREAD

**Issue by stuieordie** [rvojcik/rtapi#7] opened 2019-02-04 18:59 UTC
Great work so far, is there any plan to add the ability to link an object to rackspace?

**Comment by rvojcik** [comment] 2019-02-21 14:31
Hi, thank you much for interest. Maybe in the future. Unfortunately I have no much time for this now, sorry.

**Comment by rvojcik** [comment] 2019-02-21 14:31
Duplicate of #1

**Closed by rvojcik** 2019-02-21 14:31 UTC
Labels: duplicate
